//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_id
    {
        public product_id()
        {
            this.C_order_ = new HashSet<C_order_>();
            this.discounts = new HashSet<discount>();
        }
    
        public int product_id1 { get; set; }
        public string name { get; set; }
        public string details { get; set; }
        public decimal price { get; set; }
        public int serial_number { get; set; }
        public string category { get; set; }
    
        public virtual ICollection<C_order_> C_order_ { get; set; }
        public virtual ICollection<discount> discounts { get; set; }
    }
}
