//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_id
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string first_Name { get; set; }
        public string last_Name { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public Nullable<int> balance { get; set; }
    
        public virtual discount discount { get; set; }
    }
}
